/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Allergy.Allergy;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madhuja
 */
public class ManageAllergiesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAllergiesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Allergy allergy;
    public ManageAllergiesJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.allergy = null;
        populateAllergy();
    }
    
    public void populateAllergy(){
        DefaultTableModel model = (DefaultTableModel) tblAllergies.getModel();
        model.setRowCount(0);
        for(Allergy a : system.getAllergyList()){
            Object [] row = new Object[model.getColumnCount()];
            row[0] = a;
            row[1] = a.getSymptoms();
            row[2] = a.getPrecautions();
            row[3] = a.getRemedy();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllergies = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAllergyBy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSymptoms = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrecautions = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRemedies = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        comboSensorParameter = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtThreshold = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        btnBack4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblAllergies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allergy by", "Symptoms", "Precautions", "Remedies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllergies);
        if (tblAllergies.getColumnModel().getColumnCount() > 0) {
            tblAllergies.getColumnModel().getColumn(0).setResizable(false);
            tblAllergies.getColumnModel().getColumn(1).setResizable(false);
            tblAllergies.getColumnModel().getColumn(2).setResizable(false);
            tblAllergies.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setText("Allergy By:");

        jLabel3.setText("Symptoms:");

        txtSymptoms.setColumns(20);
        txtSymptoms.setRows(5);
        jScrollPane2.setViewportView(txtSymptoms);

        jLabel4.setText("Precautions:");

        txtPrecautions.setColumns(20);
        txtPrecautions.setRows(5);
        jScrollPane3.setViewportView(txtPrecautions);

        jLabel5.setText("Remedies:");

        txtRemedies.setColumns(20);
        txtRemedies.setRows(5);
        jScrollPane4.setViewportView(txtRemedies);

        jLabel6.setText("Sensor Parameter:");

        comboSensorParameter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollen Grains", "UV Index", "Dander", "Dust Mites" }));
        comboSensorParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSensorParameterActionPerformed(evt);
            }
        });

        jLabel7.setText("Threshold:");

        txtThreshold.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtThresholdKeyPressed(evt);
            }
        });

        btnBack1.setBackground(new java.awt.Color(0, 153, 153));
        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("<<");
        btnBack1.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack1.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Manage Allergies");

        btnBack2.setBackground(new java.awt.Color(0, 153, 153));
        btnBack2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("Save");
        btnBack2.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack2.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        btnBack3.setBackground(new java.awt.Color(0, 153, 153));
        btnBack3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnBack3.setText("Edit");
        btnBack3.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack3.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnBack4.setBackground(new java.awt.Color(0, 153, 153));
        btnBack4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack4.setForeground(new java.awt.Color(255, 255, 255));
        btnBack4.setText("Delete");
        btnBack4.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack4.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAllergyBy)
                                            .addComponent(jScrollPane2)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32)
                                        .addComponent(comboSensorParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel7)
                                        .addGap(38, 38, 38)
                                        .addComponent(txtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(505, 505, 505)
                                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(48, 48, 48))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(696, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAllergyBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboSensorParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(571, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
          this.allergy = null;
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
                if(!(txtAllergyBy.getText().isEmpty() || txtSymptoms.getText().isEmpty() || txtPrecautions.getText().isEmpty() || txtRemedies.getText().isEmpty())){
            if(this.allergy == null){
                this.allergy = new Allergy();
                system.getAllergyList().add(allergy);
            }
            this.allergy.setAllergy_by(txtAllergyBy.getText());
            this.allergy.setSymptoms(txtSymptoms.getText());
            this.allergy.setPrecautions(txtPrecautions.getText());
            this.allergy.setRemedy(txtRemedies.getText());
            this.allergy.setSensorParameter((String) comboSensorParameter.getSelectedItem());
            this.allergy.setThreshold(Double.parseDouble(txtThreshold.getText()));
            JOptionPane.showMessageDialog(null, "Allergy has been added successfully!");
            this.allergy = null;
            populateAllergy(); 
        }else{
            JOptionPane.showMessageDialog(null, "Fields cannot be blank!","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
                int selectedRow = tblAllergies.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select row","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            this.allergy = (Allergy) tblAllergies.getValueAt(selectedRow,0);
            txtAllergyBy.setText(this.allergy.getAllergy_by());
            txtSymptoms.setText(this.allergy.getSymptoms());
            txtPrecautions.setText(this.allergy.getPrecautions());
            txtRemedies.setText(this.allergy.getRemedy());
            comboSensorParameter.setSelectedItem(this.allergy.getSensorParameter());
            txtThreshold.setText(String.valueOf(this.allergy.getThreshold()));
        }
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        // TODO add your handling code here:
        
                int selectedRow = tblAllergies.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select row","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            this.allergy = (Allergy) tblAllergies.getValueAt(selectedRow,0);
            system.getAllergyList().remove(this.allergy);
            JOptionPane.showMessageDialog(null,"Allergy Details deleted successfully!");
            this.allergy = null;
        }
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void comboSensorParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSensorParameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSensorParameterActionPerformed

    private void txtThresholdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThresholdKeyPressed
        // TODO add your handling code here:
                       int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)
                || (key == evt.VK_BACK_SPACE || key == evt.VK_DELETE)) {
            txtThreshold.setEditable(true);
            txtThreshold.setBackground(Color.WHITE);
        } else {

            txtThreshold.setEditable(false);
            txtThreshold.setBackground(Color.red);

        }

    }//GEN-LAST:event_txtThresholdKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JComboBox<String> comboSensorParameter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAllergies;
    private javax.swing.JTextField txtAllergyBy;
    private javax.swing.JTextArea txtPrecautions;
    private javax.swing.JTextArea txtRemedies;
    private javax.swing.JTextArea txtSymptoms;
    private javax.swing.JTextField txtThreshold;
    // End of variables declaration//GEN-END:variables
}
