/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import Validation.Validation;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Madhuja
 */
public class SystemAdminWorkAreaJPanell extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanell
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Network network;
    Enterprise enterprise;
    Employee employee;
    public SystemAdminWorkAreaJPanell(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        network = null;
        enterprise = null;
        employee = null;
        populateCountryCombo();
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            comboEnterpriseType.addItem(type);
        }
        populateEnterprise();
    }
    
    public void populateCountryCombo(){
        
        ArrayList<String> country = new ArrayList<String>();
        comboCountry.removeAllItems();
        for(Network n : system.getNetworkList()){
            if(country.contains(n.getCountry().toString())){
                continue;
            }else{
                country.add(n.getCountry());
            }
        }
        for(String s : country){
            comboCountry.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox<>();
        txtCountry = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        btnNetworkSave = new javax.swing.JButton();
        btnNetworkEdit = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        comboEnterpriseName = new javax.swing.JComboBox();
        txtEnterpriseName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEnterpriseContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEnterpriseLocation = new javax.swing.JTextField();
        btnEnterpriseEdit = new javax.swing.JButton();
        btnEnterpriseSave = new javax.swing.JButton();
        comboEnterpriseType = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmployeeContact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        comboEmployeeName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        btnEmployeeEdit = new javax.swing.JButton();
        btnEmployeeSave = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox<>();
        comboCity = new javax.swing.JComboBox<>();
        comboCountry = new javax.swing.JComboBox<>();
        btnManageMedicines = new javax.swing.JButton();
        btnManageAllergies = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Enterprise:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("System Admin Work Area");

        comboState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboStateItemStateChanged(evt);
            }
        });

        btnNetworkSave.setText("Save");
        btnNetworkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkSaveActionPerformed(evt);
            }
        });

        btnNetworkEdit.setText("Edit");
        btnNetworkEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkEditActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Network Selection:");

        comboEnterpriseName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEnterpriseNameItemStateChanged(evt);
            }
        });

        jLabel1.setText("Enterprise Name:");

        jLabel5.setText("Contact:");

        jLabel6.setText("Location:");

        btnEnterpriseEdit.setText("Edit");
        btnEnterpriseEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseEditActionPerformed(evt);
            }
        });

        btnEnterpriseSave.setText("Save");
        btnEnterpriseSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseSaveActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Employee:");

        jLabel8.setText("Name:");

        jLabel9.setText("Gender:");

        jLabel10.setText("Contact:");

        jLabel11.setText("Email:");

        txtEmployeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeEmailActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("User Account:");

        jLabel13.setText("User Name:");

        jLabel14.setText("Password:");

        btnEmployeeEdit.setText("Edit");
        btnEmployeeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeEditActionPerformed(evt);
            }
        });

        btnEmployeeSave.setText("Save");
        btnEmployeeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeSaveActionPerformed(evt);
            }
        });

        jLabel15.setText("Country");

        jLabel16.setText("State");

        jLabel17.setText("City");

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));

        comboCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCityItemStateChanged(evt);
            }
        });

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCountryItemStateChanged(evt);
            }
        });

        btnManageMedicines.setText("Manage Medicines");
        btnManageMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMedicinesActionPerformed(evt);
            }
        });

        btnManageAllergies.setText("Manage Allergies");
        btnManageAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAllergiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboEnterpriseName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEnterpriseContact, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEnterpriseLocation))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnterpriseEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnterpriseSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEmployeeSave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEmployeeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmployeeContact, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel15))
                            .addComponent(comboCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel16)
                                .addGap(193, 193, 193)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(94, 94, 94)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(132, 132, 132)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNetworkEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNetworkSave, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(196, 347, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnManageAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(btnManageMedicines)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetworkEdit)
                    .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetworkSave))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEnterpriseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnterpriseSave))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txtEnterpriseContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEnterpriseEdit))
                            .addGap(36, 36, 36))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnEmployeeEdit)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmployeeContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployeeSave))
                .addGap(17, 17, 17)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAllergies)
                    .addComponent(btnManageMedicines))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeEmailActionPerformed

    private void comboStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboStateItemStateChanged
        // TODO add your handling code here:
        ArrayList<Network> city = new ArrayList<Network>();
        comboCity.removeAllItems();
        for(Network n : system.getNetworkList()){
            if(n.getState().equals(comboState.getSelectedItem())){
                if(city.contains(n)){
                    continue;
                }else{
                    city.add(n);
                }
            }
        }
        for(Network n : city){
            comboCity.addItem(n);
        }
//        populateEnterprise();
    }//GEN-LAST:event_comboStateItemStateChanged

    public void populateEnterprise(){
        Network n = (Network)comboCity.getSelectedItem();
        if(n!=null){
            System.out.println(n);
            comboEnterpriseName.removeAllItems();
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                System.out.println("A");
                comboEnterpriseName.addItem(e);
            }
                System.out.println("B");

            if(comboEnterpriseName.getSelectedItem()==null){
                System.out.println("C");
                return;
            }else{
              comboEnterpriseType.setSelectedItem(((Enterprise)comboEnterpriseName.getSelectedItem()).getEnterpriseType());
            }
        }
        populateEmployee();
    }   
    
    public void populateEmployee(){
        enterprise = (Enterprise) comboEnterpriseName.getSelectedItem();
        if(enterprise!=null){
            comboEmployeeName.removeAllItems();
            for(Employee emp : enterprise.getEmployeeDirectory().getEmployeeList()){
                comboEmployeeName.addItem(emp);
            }
        }
        enterprise = null;
    }
    
    private void btnNetworkEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkEditActionPerformed
        // TODO add your handling code here:
        this.network = (Network)comboCity.getSelectedItem();
        txtCountry.setText(network.getCountry());
        txtState.setText(network.getState());
        txtCity.setText(network.getCity());
    }//GEN-LAST:event_btnNetworkEditActionPerformed

    private void btnNetworkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkSaveActionPerformed
        // TODO add your handling code here:
        if(txtCountry.getText().isEmpty() || txtState.getText().isEmpty() || txtCity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the details!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            if(network==null){
                network = new Network();
                system.getNetworkList().add(network);
                JOptionPane.showMessageDialog(null, "The Network has been added successfully!");
            }else{
                JOptionPane.showMessageDialog(null, "The Network has been updated successfully!");
            }
            network.setCountry(txtCountry.getText());
            network.setState(txtState.getText());
            network.setCity(txtCity.getText());
            txtCountry.setText("");
            txtState.setText("");
            txtCity.setText("");
            network = null;
        }
        populateCountryCombo();
    }//GEN-LAST:event_btnNetworkSaveActionPerformed

    private void btnEnterpriseSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseSaveActionPerformed
        // TODO add your handling code here:
        network = (Network) comboCity.getSelectedItem();
        if(txtEnterpriseName.getText().isEmpty() || txtEnterpriseContact.getText().isEmpty() || txtEnterpriseLocation.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the details for the Enterprise!","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println(Pattern.matches("[1-9]{1}[0-9]{9}", txtEnterpriseContact.getText()));
            if(!Pattern.matches("[1-9]{1}[0-9]{9}", txtEnterpriseContact.getText())){
                JOptionPane.showMessageDialog(null, "Please enter the contact number correctly!");
                return;
            }
            if(enterprise == null){
                Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboEnterpriseType.getSelectedItem();
                enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txtEnterpriseName.getText(), type);
                JOptionPane.showMessageDialog(null, "Enterprise has been added successfully!");
            }else{
                JOptionPane.showMessageDialog(null, "Enterprise has been updated successfully!");
            }
            enterprise.setName(txtEnterpriseName.getText());
            enterprise.setContactNo(txtEnterpriseContact.getText());
            enterprise.setLocation(txtEnterpriseLocation.getText());
            txtEnterpriseName.setText("");
            txtEnterpriseContact.setText("");
            txtEnterpriseLocation.setText("");
        }
        populateEnterprise();
        enterprise = null;
        network = null;
    }//GEN-LAST:event_btnEnterpriseSaveActionPerformed

    private void btnEnterpriseEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseEditActionPerformed
        // TODO add your handling code here:
        enterprise = (Enterprise)comboEnterpriseName.getSelectedItem();
        txtEnterpriseName.setText(enterprise.getName());
        txtEnterpriseContact.setText(enterprise.getContactNo());
        txtEnterpriseLocation.setText(enterprise.getLocation());
        comboEnterpriseType.setSelectedItem(enterprise.getEnterpriseType());
    }//GEN-LAST:event_btnEnterpriseEditActionPerformed

    private void btnEmployeeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeSaveActionPerformed
        // TODO add your handling code here:
        if(txtEmployeeName.getText().isEmpty() || txtEmployeeEmail.getText().isEmpty() || txtEmployeeContact.getText().isEmpty() || txtUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the details for the Enterprise!","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println(Pattern.matches("[1-9]{1}[0-9]{9}", txtEmployeeContact.getText()));
            if(!Pattern.matches("[1-9]{1}[0-9]{9}", txtEmployeeContact.getText())){
                JOptionPane.showMessageDialog(null, "Please enter the contact number correctly!");
                return;
            }
            if(!Validation.emailVal(txtEmployeeEmail.getText())){
                JOptionPane.showMessageDialog(null, "Please enter the email address correctly!");
                return;
            }
            enterprise = (Enterprise) comboEnterpriseName.getSelectedItem();
            if(employee == null){
                employee = new Employee();
                enterprise.getEmployeeDirectory().getEmployeeList().add(employee);
                JOptionPane.showMessageDialog(null, "Enterprise has been added successfully!");
            }else{
                JOptionPane.showMessageDialog(null, "Enterprise has been updated successfully!");    
            }
            employee.setName(txtEmployeeName.getText());
            employee.setGender(comboGender.getSelectedItem().toString());
            employee.setContact(txtEmployeeContact.getText());
            employee.setEmailID(txtEmployeeEmail.getText());
            UserAccount user;
            if(txtUserPassword.isEnabled()){
                user = new UserAccount();
                enterprise.getUserAccountDirectory().getUserAccountList().add(user);
                String password = String.valueOf(txtUserPassword.getPassword());
                user.setPassword(password);
            }else{
                user = employee.getUserAccount();
            }
            user.setUsername(txtUsername.getText());
            user.setEmployee(employee);
            user.setRole(new AdminRole());
            employee.setUserAccount(user);
        }   
        populateEmployee();
        employee = null;
        enterprise = null;
    }//GEN-LAST:event_btnEmployeeSaveActionPerformed

    private void btnEmployeeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeEditActionPerformed
        // TODO add your handling code here:
        employee = (Employee)comboEmployeeName.getSelectedItem();
        txtEmployeeContact.setText(employee.getContact());
        txtEmployeeEmail.setText(employee.getEmailID());
        txtEmployeeName.setText(employee.getName());
        comboGender.setSelectedItem(employee.getGender());
        txtUsername.setText(employee.getUserAccount().getUsername());
        txtUsername.setEnabled(false);
        txtUserPassword.setEnabled(false);
    }//GEN-LAST:event_btnEmployeeEditActionPerformed

    private void comboCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCountryItemStateChanged
        // TODO add your handling code here:
        ArrayList<String> state = new ArrayList<String>();
        comboState.removeAllItems();
        for(Network n : system.getNetworkList()){
            if(n.getCountry().equals(comboCountry.getSelectedItem())){
                if(state.contains(n)){
                    continue;
                }else{
                    state.add(n.getState());
                }
            }
        }
        for(String s : state){
            comboState.addItem(s);
        }
    }//GEN-LAST:event_comboCountryItemStateChanged

    private void comboCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCityItemStateChanged
        // TODO add your handling code here:
        populateEnterprise();
    }//GEN-LAST:event_comboCityItemStateChanged

    private void comboEnterpriseNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEnterpriseNameItemStateChanged
        // TODO add your handling code here:
        populateEmployee();
    }//GEN-LAST:event_comboEnterpriseNameItemStateChanged

    private void btnManageMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMedicinesActionPerformed
        // TODO add your handling code here:
        ManageMedicinesJPanel manageMedicineJPanel = new ManageMedicinesJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageMedicinesJPanel", manageMedicineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMedicinesActionPerformed

    private void btnManageAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAllergiesActionPerformed
        // TODO add your handling code here:
        ManageAllergiesJPanel panel = new ManageAllergiesJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageAllergiesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAllergiesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeEdit;
    private javax.swing.JButton btnEmployeeSave;
    private javax.swing.JButton btnEnterpriseEdit;
    private javax.swing.JButton btnEnterpriseSave;
    private javax.swing.JButton btnManageAllergies;
    private javax.swing.JButton btnManageMedicines;
    private javax.swing.JButton btnNetworkEdit;
    private javax.swing.JButton btnNetworkSave;
    private javax.swing.JComboBox<Network> comboCity;
    private javax.swing.JComboBox<String> comboCountry;
    private javax.swing.JComboBox<Employee> comboEmployeeName;
    private javax.swing.JComboBox comboEnterpriseName;
    private javax.swing.JComboBox comboEnterpriseType;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboState;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmployeeContact;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEnterpriseContact;
    private javax.swing.JTextField txtEnterpriseLocation;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtState;
    private javax.swing.JPasswordField txtUserPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
