/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.User;

import Business.EcoSystem;
import Business.EmailConfig.EmailConfig;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Conversation;
import Business.WorkQueue.IssueWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kothari
 */
public class RaiseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RaiseRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount ua;
    EcoSystem system;
    public RaiseRequestJPanel(JPanel userProcessContainer, UserAccount ua, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
        populateCombo();
    }

    public void populateCombo(){
        for(Network n : system.getNetworkList()){
            comboNetwork.addItem(n);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSymptoms = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        lblImagePath = new javax.swing.JLabel();
        btnRR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox<>();
        btnBack1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Raise a New Request");

        jLabel2.setText("Issue Title:");

        jLabel3.setText("Issue Description:");

        jLabel4.setText("Image Upload:");
        jLabel4.setEnabled(false);

        txtSymptoms.setColumns(20);
        txtSymptoms.setRows(5);
        jScrollPane1.setViewportView(txtSymptoms);

        btnUpload.setText("Upload Image");
        btnUpload.setEnabled(false);

        lblImagePath.setText("jLabel5");
        lblImagePath.setEnabled(false);

        btnRR.setText("Raise Request");
        btnRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRRActionPerformed(evt);
            }
        });

        jLabel5.setText("Current Area:");

        btnBack1.setBackground(new java.awt.Color(0, 153, 153));
        btnBack1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("<<");
        btnBack1.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack1.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnRR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpload)
                                .addGap(18, 18, 18)
                                .addComponent(lblImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboNetwork, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnUpload)
                    .addComponent(lblImagePath))
                .addGap(18, 18, 18)
                .addComponent(btnRR)
                .addGap(31, 31, 31)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void sendEmail(UserAccount ua,WorkRequest wr)
    {        	
        String toAddress = ua.getEmployee().getEmailID();
        String subject = "Issue Request with IR No. "+wr.getId()+" has been raised successfully";
        String message = "Issue Request Raised!";
        try {
                EmailConfig emailConfig= new EmailConfig();
                Properties smtpProperties = emailConfig.loadProperties();
                emailConfig.sendEmail(smtpProperties, toAddress, subject, message);

//			JOptionPane.showMessageDialog(this, 
//					"The e-mail has been sent successfully!");

        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                                "Error while sending the e-mail: " + ex.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void btnRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRRActionPerformed
        // TODO add your handling code here:
        
        
        IssueWorkRequest wr = new IssueWorkRequest();
        Conversation c = new Conversation();
        c.setMsg(txtSymptoms.getText());
        c.setUa(ua);
        wr.getConversation().add(c);
        wr.setTitle(txtTitle.getText());
        wr.setIssueRaiser(ua);
        wr.setStatus("Request Raised");
        ua.getWorkQueue().getWorkRequestList().add(wr);
        
        Network n = (Network)comboNetwork.getSelectedItem();
        
        for(Enterprise enterprise : n.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof HealthEnterprise){
                for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org instanceof DoctorOrganization){
                        org.getWorkQueue().getWorkRequestList().add(wr);
                    }
                }
            }
        }
        ///////////////////Email sending functionality///////////////////////////////////////
                sendEmail(ua,wr);
        ///////////////////Email sending functionality///////////////////////////////////////
        
        JOptionPane.showMessageDialog(null, "Request has been raised successfully!");
        
        userProcessContainer.remove(this);
        ((ManageRequestsJPanel)userProcessContainer.getComponents()[userProcessContainer.getComponents().length-1]).populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnRRActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnRR;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<Network> comboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JTextArea txtSymptoms;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
