/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.User;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacistEnterprise;
import Business.Inventory.Inventory;
import Business.Network.Network;
import Business.Organization.InventoryManager;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IssueWorkRequest;
import Business.WorkQueue.PrescriptionItems;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kothari
 */
public class ViewPharmacistsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPharmacistsJPanel
     */
    private JPanel userProcessContainer;
    private Network n;
    private UserAccount ua;
    
    public ViewPharmacistsJPanel(JPanel userProcessContainer, UserAccount ua, Network n) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.n = n;
        this.ua = ua;
        populatePharmacists();
    }

    public void populatePharmacists(){
        DefaultTableModel model = (DefaultTableModel)tblPharmacist.getModel();
        model.setRowCount(0);
        boolean set = false;
        for(WorkRequest wr : ua.getWorkQueue().getWorkRequestList()){
            if(set == false){
            System.out.println("A");
            if(wr instanceof IssueWorkRequest){
                for(PrescriptionItems pi : ((IssueWorkRequest)wr).getPrescription().getPrescriptionItems()){
                    System.out.println("B");
                    if(!pi.isStatus()){
                        System.out.println("C");
                        for(Enterprise ent : n.getEnterpriseDirectory().getEnterpriseList()){
                            System.out.println("D");
                            if(ent instanceof PharmacistEnterprise){
                                System.out.println("E");
                                for(Organization org : ent.getOrganizationDirectory().getOrganizationList()){
                                    System.out.println("F");
                                    if(org instanceof InventoryManager){
                                        System.out.println("G");
                                        for(Inventory inv : ((InventoryManager)org).getInventoryList()){
                                            System.out.println("H");
                                            if(pi.getMedicine().equals(inv.getMedicine())){
                                                System.out.println("I");
                                                if(inv.getQuantity()>0){
                                                    System.out.println("J");
                                                    Object [] row = new Object[model.getColumnCount()];
                                                    row[0] = ent;
                                                    model.addRow(row);
                                                    set = true;
                                                    break;
                                                }
                                                set = false;
                                            }
                                        }
                                    }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPharmacist = new javax.swing.JTable();
        lblPharmacist = new javax.swing.JLabel();

        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("View Nearby Pharmacists");

        tblPharmacist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pharmacist Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPharmacist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPharmacistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPharmacist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                                .addComponent(lblPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblPharmacistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPharmacistMouseClicked
        // TODO add your handling code here:
        PharmacistEnterprise ent = (PharmacistEnterprise) tblPharmacist.getValueAt(tblPharmacist.getSelectedRow(), 0);
        String print = "<html><b>"+ent.getName()+"</b><br>"+"<b>Location:</b> "+ent.getLocation()+"<br><b>Contact No:</b>"+ent.getContactNo();
        lblPharmacist.setText(print);
    }//GEN-LAST:event_tblPharmacistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPharmacist;
    private javax.swing.JTable tblPharmacist;
    // End of variables declaration//GEN-END:variables
}
