---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csye7374-app-profile
data:
  profile: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csye7374-rc
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: csye7374
  template:
    metadata:
      labels:
        app: csye7374
    spec:
      initContainers:
      - name: kafka-init
        image: ecr_repo/kafka:latest
        # command: ['ls','./bin/kafka-topics.sh --zookeeper csye7374-zookeeper:2181 --create --if-not-exists --partitions 1 --replication-factor 3 --topic csye7374']
      - name: init-container-02
        image: busybox:1.30
        command: ['sh', '-c', 'sleep 10']
      containers:
      - image: ecr_repo/csye7374:latest   
        name: csye7374 
        env:

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-profile
              key: profile
        
        - name: bucketName                
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-bucket
              key: bucket_name
        
        - name: SPRING_DATASOURCE_URL              
          valueFrom:                     
            configMapKeyRef:             
              name: db-endpoint     
              key: db_endpoint
        
        - name: SPRING_DATASOURCE_USERNAME               
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config     
              key: DB_USER
        
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config
              key: DB_PASSWD

        - name: KAFKA_SERVICE_IP
          valueFrom:                     
            configMapKeyRef:             
              name: kafka-ip
              key: kafka_service_ip

        - name: KAFKA_SERVICE_PORT
          valueFrom:                     
            configMapKeyRef:             
              name: kafka-port
              key: kafka_service_port

        - name: KAFKA_TOPIC_NAME
          valueFrom:                     
            configMapKeyRef:             
              name: kafka-topic
              key: kafka_topic_name
        livenessProbe:
          httpGet:
            path: /user/testdbs3
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /user/testdbs3
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 60        
        ports:
        - containerPort: 8080    
          protocol: TCP
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-elb
spec:
  type: LoadBalancer             
  ports:
  - port: 80                 
    targetPort: 8080         
    nodePort: 30130          
  selector:
    app: csye7374
  