/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SensorAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SensorEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SensorOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madhuja
 */
public class SensorAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SensorAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    EcoSystem system;
    public SensorAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Organization organization,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.system = system;
        
        populateNetworkCombo();
        populateSensorValues();
    }
    
    public void populateNetworkCombo(){
        for(Network n : system.getNetworkList()){
            comboNetwork.addItem(n);
        }
    }
    
    public void populateSensorValues(){
        Network n = (Network)comboNetwork.getSelectedItem();
        SensorEnterprise se = null;
        for(Enterprise enterprise : n.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof SensorEnterprise){
                se = (SensorEnterprise) enterprise;
                break;
            }
        }
        SensorOrganization so = null;
        for(Organization org : se.getOrganizationDirectory().getOrganizationList()){
            so = (SensorOrganization) org;
            break;
        }
        
        DefaultTableModel model = (DefaultTableModel)tblSensorValues.getModel();
        model.setRowCount(0);
        Object row[] = new Object[model.getColumnCount()];
        row[0] = "Temperature";
        row[1] = so.getSensorValues().getTemperature();
        model.addRow(row);
        row[0] = "Wind Speed";
        row[1] = so.getSensorValues().getWindSpeed();
        model.addRow(row);
        row[0] = "Humidity";
        row[1] = so.getSensorValues().getHumidity();
        model.addRow(row);
        row[0] = "Air Quality";
        row[1] = so.getSensorValues().getAirQuality();
        model.addRow(row);
        row[0] = "Pollen Ratio";
        row[1] = so.getSensorValues().getPollenRatio();
        model.addRow(row);
        row[0] = "UV Index";
        row[1] = so.getSensorValues().getUvIndex();
        model.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSensorValues = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Sensor Admin Work Area");

        jLabel2.setText("Select Network:");

        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });

        tblSensorValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attribute", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSensorValues);
        if (tblSensorValues.getColumnModel().getColumnCount() > 0) {
            tblSensorValues.getColumnModel().getColumn(0).setResizable(false);
            tblSensorValues.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
        populateSensorValues();
    }//GEN-LAST:event_comboNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSensorValues;
    // End of variables declaration//GEN-END:variables
}
