apiVersion: v1
kind: Pod
metadata:
  name: testclient
spec:
  containers:
  - name: kafka
    image: 757638245294.dkr.ecr.us-east-1.amazonaws.com/kafka:latest
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"