/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabOrganization;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Results.Result;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jigar
 */
public class LabOrganizationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabOrganizationWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    
    public LabOrganizationWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        populateGlobalWorkRequests();
        populateSelfWorkRequests();
    }
    
    public void populateGlobalWorkRequests(){
        DefaultTableModel model = (DefaultTableModel)tblGlobalWR.getModel();
        model.setRowCount(0);
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof LabOrganization){
                for(WorkRequest wr : org.getWorkQueue().getWorkRequestList()){
                    if(((LabTestWorkRequest)wr).getLabAssigned()==null){
                        Object [] row = new Object[model.getColumnCount()];
                        row[0] = wr;
                        row[1] = wr.getTitle();
                        model.addRow(row);
                    }
                }
            }
        }
    }
    
    public void populateSelfWorkRequests(){
        DefaultTableModel model = (DefaultTableModel)tblWR.getModel();
        model.setRowCount(0);
        
        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            if(wr.getStatus()=="Completed"){
                Object [] row = new Object[model.getColumnCount()];
                row[0] = wr;
                row[1] = wr.getTitle();
                model.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGlobalWR = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblWR = new javax.swing.JTable();
        lblAttribute = new javax.swing.JLabel();
        txtTestAttribute = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        btnOWRRefresh = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        btnBack5 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("LabOrganization Work Area");

        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Global Work Requests:");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Attribute", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResult);
        if (tblResult.getColumnModel().getColumnCount() > 0) {
            tblResult.getColumnModel().getColumn(0).setResizable(false);
            tblResult.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Own Work Requests:");

        tblGlobalWR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGlobalWR);
        if (tblGlobalWR.getColumnModel().getColumnCount() > 0) {
            tblGlobalWR.getColumnModel().getColumn(0).setResizable(false);
            tblGlobalWR.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Test Results:");

        tblWR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWRMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblWR);
        if (tblWR.getColumnModel().getColumnCount() > 0) {
            tblWR.getColumnModel().getColumn(0).setResizable(false);
            tblWR.getColumnModel().getColumn(1).setResizable(false);
        }

        lblAttribute.setForeground(new java.awt.Color(255, 153, 0));
        lblAttribute.setText("Test Attribute:");
        lblAttribute.setEnabled(false);

        txtTestAttribute.setEnabled(false);

        lblMessage.setForeground(new java.awt.Color(255, 153, 0));
        lblMessage.setText("Message:");
        lblMessage.setEnabled(false);

        txtMessage.setEnabled(false);
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 153, 153));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setMaximumSize(new java.awt.Dimension(200, 200));
        btnRefresh.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAssignToMe.setBackground(new java.awt.Color(0, 153, 153));
        btnAssignToMe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.setMaximumSize(new java.awt.Dimension(200, 200));
        btnAssignToMe.setMinimumSize(new java.awt.Dimension(200, 200));
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnOWRRefresh.setBackground(new java.awt.Color(0, 153, 153));
        btnOWRRefresh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOWRRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnOWRRefresh.setText("Refresh");
        btnOWRRefresh.setMaximumSize(new java.awt.Dimension(200, 200));
        btnOWRRefresh.setMinimumSize(new java.awt.Dimension(200, 200));
        btnOWRRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOWRRefreshActionPerformed(evt);
            }
        });

        btnComplete.setBackground(new java.awt.Color(0, 153, 153));
        btnComplete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnComplete.setText("Complete");
        btnComplete.setMaximumSize(new java.awt.Dimension(200, 200));
        btnComplete.setMinimumSize(new java.awt.Dimension(200, 200));
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnBack5.setBackground(new java.awt.Color(0, 153, 153));
        btnBack5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack5.setForeground(new java.awt.Color(255, 255, 255));
        btnBack5.setText("Add results");
        btnBack5.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack5.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 153, 153));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setMaximumSize(new java.awt.Dimension(200, 200));
        btnSubmit.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.setMaximumSize(new java.awt.Dimension(200, 200));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAttribute)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTestAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOWRRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOWRRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTestAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttribute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateGlobalWorkRequests();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblGlobalWR.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a Work Request to assign it to yourself!");
        }else{
            WorkRequest wr = (WorkRequest) tblGlobalWR.getValueAt(selectedRow, 0);
            ((LabTestWorkRequest)wr).setLabAssigned(account);
            account.getWorkQueue().getWorkRequestList().add(wr);
            wr.setStatus("Assigned");
            populateGlobalWorkRequests();
            populateSelfWorkRequests();
        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnOWRRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOWRRefreshActionPerformed
        // TODO add your handling code here:
        populateSelfWorkRequests();
    }//GEN-LAST:event_btnOWRRefreshActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblGlobalWR.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a Work Request!");
        }else{
            WorkRequest wr = (WorkRequest) tblGlobalWR.getValueAt(selectedRow, 0);
            wr.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "Lab Test completed successfully!");
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        // TODO add your handling code here:
        lblAttribute.setEnabled(true);
        lblMessage.setEnabled(true);
        txtTestAttribute.setEnabled(true);
        txtMessage.setEnabled(true);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtMessage.getText().isEmpty() || txtTestAttribute.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the details of the test result!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int selectedRow = tblGlobalWR.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a Work Request!");
        }else{
            WorkRequest wr = (WorkRequest) tblGlobalWR.getValueAt(selectedRow, 0);
            Result r = new Result();
            r.setAttribute(txtTestAttribute.getText());
            r.setResult(txtMessage.getText());
            ((LabTestWorkRequest)wr).getTestResults().add(r);
            wr.setStatus("Pending");
            lblAttribute.setEnabled(true);
            lblMessage.setEnabled(true);
            txtTestAttribute.setEnabled(true);
            txtMessage.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Test Result added successfully!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblWRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWRMouseClicked
        // TODO add your handling code here:
        populateTestResults();
    }//GEN-LAST:event_tblWRMouseClicked

    public void populateTestResults(){
        int selectedRow = tblWR.getSelectedRow();
        LabTestWorkRequest lwr = (LabTestWorkRequest)tblWR.getValueAt(selectedRow, 0);
        DefaultTableModel model = (DefaultTableModel)tblWR.getModel();
        model.setRowCount(0);
        
        for(Result result : lwr.getTestResults()){
            Object [] row = new Object[model.getColumnCount()];
            row[0] = result.getAttribute();
            row[1] = result.getResult();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnOWRRefresh;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAttribute;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblGlobalWR;
    private javax.swing.JTable tblResult;
    private javax.swing.JTable tblWR;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtTestAttribute;
    // End of variables declaration//GEN-END:variables
}
